server:
  port: 8080

spring:
  application:
    name: "erp-system"


  datasource:
    url: jdbc:mysql://localhost:3306/db_erp_system
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    locations: "db/migration"
    baseline-on-migrate: false

  devtools:
    restart:
      enabled: true