ALTER TABLE tb_funcionarios
    MODIFY COLUMN cpf VARCHAR(11) NOT NULL UNIQUE,
    MODIFY COLUMN rg VARCHAR(13) NOT NULL UNIQUE,
    MODIFY COLUMN reservista VARCHAR(12) UNIQUE,
    MODIFY COLUMN email VARCHAR(255) NOT NULL UNIQUE,
    MODIFY COLUMN matricula VARCHAR(20) UNIQUE;

