ALTER TABLE tb_fornecedores
    MODIFY COLUMN razaoSocial VARCHAR(255) NOT NULL UNIQUE,
    MODIFY COLUMN cnpj VARCHAR(14) NOT NULL UNIQUE,
    MODIFY COLUMN inscricaoEstadual VARCHAR(9) UNIQUE,
    MODIFY COLUMN inscricaoMunicipal VARCHAR(11) UNIQUE;


ALTER TABLE tb_clientes
    MODIFY COLUMN razaoSocial VARCHAR(255) NOT NULL UNIQUE,
    MODIFY COLUMN cnpj VARCHAR(14) NOT NULL UNIQUE,
    MODIFY COLUMN inscricaoEstadual VARCHAR(9) UNIQUE,
    MODIFY COLUMN inscricaoMunicipal VARCHAR(11) UNIQUE;